name: linting, testing, building
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    pipeline:
        runs-on: ubuntu-22.04
        strategy:
            matrix:
                node-version: [20.x]

        steps:
            - uses: actions/checkout@v2
            - name: Starting Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install dependencies
              run: npm ci
            - name: Build production project
              run: npm run build:prod
            - name: Linting TypeScript
              run: npm run lint:ts
            - name: Linting SCSS
              run: npm run lint:scss
            - name: Unit testing
              run: npm run test:unit
            - name: Build Storybook
              run: xvfb-run -a npm run storybook:build
            - name: Screenshot testing
              run: xvfb-run -a npm run test:ui:ci
